# builds on PR and PUSH for branches that aren't releases. This does include PRs to main but not PUSHING to main (which
# triggers a release and is handled in release-builds.yml).
#
# Versions will have the last version tag used appended with a "-<commit hash>" and will have a non `main` branch
#
name: dev-builds
on:
  pull_request:

jobs:
  mac-os-build:
    name: Build Mac OS
    runs-on: macos-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.20'

      - name: Test
        run: |
          go test ./...

  windows-build:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.20'

      - name: Test
        run: |
          go test ./...

  linux-build:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.20'

      - name: Test
        run: |
          go test ./...